name: flutter_acrcloud
description: A Flutter plugin for the ACRCloud music recognition API. This plugin provides a simple interface for using ACRCloud to recognize music from the device's microphone.
version: 0.1.6
homepage: https://github.com/nrubin29/flutter_acrcloud

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nrubintech.flutter_acrcloud
        pluginClass: FlutterAcrcloudPlugin
      ios:
        pluginClass: FlutterAcrcloudPlugin
